### ISSUE TITLE
Modbus address change

### ISSUE THREAD

**Issue by bryanc806** [collinturney/solarshed#1]
Hi,

I recently was trying your code on 2 Wanderer's that I bought this month.  My older Wanderer worked fine with your code, but the newer devices required changing the modbus address to 255 to get them to work.  This is even though 255 is not a valid modbus address.  I tried all possible addresses (1-255)

I'm not sure what changed, but likely a firmware revision in the controller.

--bryan

**Comment by collinturney** [comment]
@bryanc806 Thank you for letting me know!!
